pipeline {
    agent any
    stages {
        stage('Bake ELK Minikube AMI') {
            steps {
                withEnv(["AWS_CONFIG_FILE=${env.AWS_CONFIG_FILE}", "AWS_SHARED_CREDENTIALS_FILE=${env.AWS_SHARED_CREDENTIALS_FILE}"]) {
                    sh """
                    	cd ${env.PROJECT_PATH}/minikube-elk/packer
               		packer init aws-amazonlinux-elk.pkr.hcl
                	packer build aws-amazonlinux-elk.pkr.hcl
                    """
                }
            }
        }
    }
}


