pipeline {
    agent any
    stages {
        stage('Bake Redis AMI') {
            steps {
                withEnv(["AWS_CONFIG_FILE=${env.AWS_CONFIG_FILE}", "AWS_SHARED_CREDENTIALS_FILE=${env.AWS_SHARED_CREDENTIALS_FILE}"]) {
                    sh """
                    	cd ${env.PROJECT_PATH}/redis/packer
                    	packer init aws-amazonlinux-redis.pkr.hcl
                    	packer build aws-amazonlinux-redis.pkr.hcl
                    """
                }
            }
        }
    }
}



