---

    - name: Installing Golang
      yum:
        name: golang
        state: latest

    - name: Go mod download
      shell: cd /home/ec2-user/calculator/ ; go mod download

    - name: Copy service to systemd
      copy:
        src: /home/ec2-user/calculator/calculator.service
        dest: /etc/systemd/system/

    - name: Daemon-reload
      systemd:
        daemon_reload: yes

    - name: Enable calculator service on boot
      systemd:
        name: calculator
        enabled: yes

