---
    - name: Install socat
      yum:
        name: socat
        state: present

    - name: Create Service to execute socat health check
      copy:
        src: /home/ec2-user/files/socat-redis-health.service
        dest: /etc/systemd/system/
        mode: 0644

    - name: Daemon-reload
      systemd:
        daemon_reload: yes

    - name: Enable socat-redis-health service
      systemd:
        name: socat-redis-health
        enabled: yes

