- name: Stack elk
  hosts: localhost
  become: true
  tasks:
     
    - name: Adicionar vm.max_map_count ao /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: 'vm.max_map_count=262144'

    - name: Reconfigar as configurações do sysctl -p
      shell: sysctl -p

    - name: Instalação do Docker
      yum:
        name: docker
        state: latest
        update_cache: true

    - name: Adicionando usuário ao grupo Docker
      user:
        name: ec2-user
        append: yes
        groups: docker

    - name: Atualizar grupo de processos para o grupo Docker
      command: newgrp docker

    - name: Iniciar o serviço do Docker
      systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Adicionando permissões ao docker
      shell: chmod 777 /var/run/docker.sock
      
    - name: Instalação do Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: "/usr/local/bin/minikube"
        mode: 'a+x'

    - name: Habilitar o encaminhamento de pacotes entre interfaces
      shell: sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf

    - name: Aplicar alterações no kernel
      shell: sysctl --system

    - name: Copiar Minikube port forward script
      copy:
        src: /home/ec2-user/files/minikube/minikube-port-forward.sh
        dest: /usr/local/bin/minikube-port-forward.sh
        mode: 0755

    - name: Copiar Minikube port forward service
      copy:
        src: /home/ec2-user/files/minikube/minikube-port-forward.service
        dest: /etc/systemd/system/minikube-port-forward.service

    - name: Recarregar systemd configuration
      systemd:
        daemon_reload: yes

    - name: Habilitar Minikube port forward service
      systemd:
        name: minikube-port-forward
        enabled: yes

    - name: Minikube start
      shell: minikube start --cpus=2 --memory=3700mb --static-ip 192.168.49.2
      become_user: ec2-user

    - name: Criar diretório para o persistent volume do elasticsearch
      file:
        path: /mnt/elasticsearch-data
        state: directory
        mode: '0755'

    - name: Copiar Minikube start service
      copy:
        src: /home/ec2-user/files/minikube/minikube-start-and-apply.service
        dest: /etc/systemd/system/minikube-start-and-apply.service

    - name: Recarregar systemd configuration
      systemd:
        daemon_reload: yes

    - name: Habilitar Minikube start service
      systemd:
        name: minikube-start-and-apply
        enabled: yes
        
